language: rust

cache: cargo

matrix:
  include:
    # Linux 32bit
    - env: TARGET=i686-unknown-linux-gnu
      os: linux
      rust: nightly
      addons:
        apt:
          # Cross compiler and cross compiled C libraries
          packages: &i686_packages
            - gcc-multilib
    - env: TARGET=i686-unknown-linux-gnu
      os: linux
      rust: stable
      addons:
        apt:
          packages: *i686_packages

    # Linux 64bit
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      rust: stable

    # macOS
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: stable

    # iOS
    - env: TARGET=x86_64-apple-ios
      os: osx
      rust: nightly
    - env: TARGET=x86_64-apple-ios
      os: osx
      rust: stable

    # Redox, which cannot build on stable due to redox_syscall crate
    - env: TARGET=x86_64-unknown-redox
      os: linux
      rust: nightly

install:
  - rustup self update
  - rustup target add $TARGET; true

script:
  # Running iOS apps on OSX requires the simulator so we skip that for now
  # Also, running Redox programs is not possible at the moment
  - if [ "$TARGET" == "x86_64-apple-ios" -o "$TARGET" == "x86_64-unknown-redox" ]; then test=0; else test=1; fi
  - if [ "$TARGET" == "x86_64-unknown-redox" ]; then build=check; else build=build; fi
  - cargo $build --target $TARGET --verbose
  - cargo $build --target $TARGET --features serde --verbose
  - cargo $build --target $TARGET --features icon_loading --verbose
  - if [ "$test" == "1" ]; then cargo test --target $TARGET --verbose; fi
  - if [ "$test" == "1" ]; then cargo test --target $TARGET --features serde --verbose; fi
  - if [ "$test" == "1" ]; then cargo test --target $TARGET --features icon_loading --verbose; fi

after_success:
  - |
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      cargo publish --token ${CRATESIO_TOKEN}
